function main() {
    // DigitalOcean API Token secret
    const DOCredentialSecretProp = new SecretPropBuilder()
        .setName("DigitalOcean Credential")
        .setSecretKind("DigitalOcean Credential")
        .build();

    // Type property - monitoring metric type (required, createOnly)
    const typeProp = new PropBuilder()
        .setName("type")
        .setKind("string")
        .setHidden(false)
        .setWidget(new PropWidgetDefinitionBuilder()
            .setKind("comboBox")
            .addOption("Droplet Load 1 Minute", "v1/insights/droplet/load_1")
            .addOption("Droplet Load 5 Minutes", "v1/insights/droplet/load_5")
            .addOption("Droplet Load 15 Minutes", "v1/insights/droplet/load_15")
            .addOption("Droplet Memory Utilization %", "v1/insights/droplet/memory_utilization_percent")
            .addOption("Droplet Disk Utilization %", "v1/insights/droplet/disk_utilization_percent")
            .addOption("Droplet CPU Utilization", "v1/insights/droplet/cpu")
            .addOption("Droplet Disk Read", "v1/insights/droplet/disk_read")
            .addOption("Droplet Disk Write", "v1/insights/droplet/disk_write")
            .addOption("Droplet Public Outbound Bandwidth", "v1/insights/droplet/public_outbound_bandwidth")
            .addOption("Droplet Public Inbound Bandwidth", "v1/insights/droplet/public_inbound_bandwidth")
            .addOption("Droplet Private Outbound Bandwidth", "v1/insights/droplet/private_outbound_bandwidth")
            .addOption("Droplet Private Inbound Bandwidth", "v1/insights/droplet/private_inbound_bandwidth")
            .addOption("Load Balancer Average CPU Utilization %", "v1/insights/lbaas/avg_cpu_utilization_percent")
            .addOption("Load Balancer Connection Utilization %", "v1/insights/lbaas/connection_utilization_percent")
            .addOption("Load Balancer Droplet Health", "v1/insights/lbaas/droplet_health")
            .addOption("Load Balancer TLS Connections Per Second %", "v1/insights/lbaas/tls_connections_per_second_utilization_percent")
            .addOption("Load Balancer HTTP 5xx Error Rate % Increase", "v1/insights/lbaas/increase_in_http_error_rate_percentage_5xx")
            .addOption("Load Balancer HTTP 4xx Error Rate % Increase", "v1/insights/lbaas/increase_in_http_error_rate_percentage_4xx")
            .addOption("Load Balancer HTTP 5xx Error Count Increase", "v1/insights/lbaas/increase_in_http_error_rate_count_5xx")
            .addOption("Load Balancer HTTP 4xx Error Count Increase", "v1/insights/lbaas/increase_in_http_error_rate_count_4xx")
            .addOption("Load Balancer High HTTP Response Time", "v1/insights/lbaas/high_http_request_response_time")
            .addOption("Load Balancer HTTP Response Time 50th Percentile", "v1/insights/lbaas/high_http_request_response_time_50p")
            .addOption("Load Balancer HTTP Response Time 95th Percentile", "v1/insights/lbaas/high_http_request_response_time_95p")
            .addOption("Load Balancer HTTP Response Time 99th Percentile", "v1/insights/lbaas/high_http_request_response_time_99p")
            .addOption("Database Load 15 Minutes", "v1/dbaas/alerts/load_15_alerts")
            .addOption("Database Memory Utilization", "v1/dbaas/alerts/memory_utilization_alerts")
            .addOption("Database Disk Utilization", "v1/dbaas/alerts/disk_utilization_alerts")
            .addOption("Database CPU Utilization", "v1/dbaas/alerts/cpu_alerts")
            .addOption("Autoscale Current Instances", "v1/droplet/autoscale_alerts/current_instances")
            .addOption("Autoscale Target Instances", "v1/droplet/autoscale_alerts/target_instances")
            .addOption("Autoscale Current CPU Utilization", "v1/droplet/autoscale_alerts/current_cpu_utilization")
            .addOption("Autoscale Target CPU Utilization", "v1/droplet/autoscale_alerts/target_cpu_utilization")
            .addOption("Autoscale Current Memory Utilization", "v1/droplet/autoscale_alerts/current_memory_utilization")
            .addOption("Autoscale Target Memory Utilization", "v1/droplet/autoscale_alerts/target_memory_utilization")
            .addOption("Autoscale Scale Up", "v1/droplet/autoscale_alerts/scale_up")
            .addOption("Autoscale Scale Down", "v1/droplet/autoscale_alerts/scale_down")
            .build())
        .setValidationFormat(Joi.string().required())
        .setDocumentation("The type of metric to monitor. This determines what metric is tracked and which entity types the alert policy applies to.")
        .build();

    // Description property (required)
    const descriptionProp = new PropBuilder()
        .setName("description")
        .setKind("string")
        .setHidden(false)
        .setWidget(new PropWidgetDefinitionBuilder()
            .setKind("text")
            .build())
        .setValidationFormat(Joi.string().required().max(255))
        .setDocumentation("A human-readable description of the alert policy.")
        .build();

    // Compare property (required)
    const compareProp = new PropBuilder()
        .setName("compare")
        .setKind("string")
        .setHidden(false)
        .setWidget(new PropWidgetDefinitionBuilder()
            .setKind("comboBox")
            .addOption("GreaterThan", "GreaterThan")
            .addOption("LessThan", "LessThan")
            .build())
        .setValidationFormat(Joi.string().required())
        .setDocumentation("The comparison operator to use when evaluating the alert condition.")
        .build();

    // Value property (required)
    const valueProp = new PropBuilder()
        .setName("value")
        .setKind("float")
        .setHidden(false)
        .setWidget(new PropWidgetDefinitionBuilder()
            .setKind("text")
            .build())
        .setValidationFormat(Joi.number().required().min(0))
        .setDocumentation("The threshold value to compare against the metric value.")
        .build();

    // Window property (required)
    const windowProp = new PropBuilder()
        .setName("window")
        .setKind("string")
        .setHidden(false)
        .setWidget(new PropWidgetDefinitionBuilder()
            .setKind("comboBox")
            .addOption("5m", "5m")
            .addOption("10m", "10m")
            .addOption("30m", "30m")
            .addOption("1h", "1h")
            .build())
        .setValidationFormat(Joi.string().required())
        .setDocumentation("The time window over which the alert condition is evaluated.")
        .build();

    // Entities property (required)
    const entitiesProp = new PropBuilder()
        .setName("entities")
        .setKind("array")
        .setHidden(false)
        .setWidget(new PropWidgetDefinitionBuilder()
            .setKind("array")
            .build())
        .setEntry(
            new PropBuilder()
            .setName("entities_item")
            .setKind("string")
            .setWidget(new PropWidgetDefinitionBuilder().setKind("text").build())
            .setValidationFormat(Joi.string())
            .setDocumentation("Entity ID (e.g., Droplet ID, Load Balancer ID)")
            .build()
        )
        .setValidationFormat(Joi.array().items(Joi.string()).required())
        .setDocumentation("An array of entity IDs that the alert policy should monitor. These are the specific resources (droplets, load balancers, etc.) that will be monitored.")
        .build();

    // Tags property (required)
    const tagsProp = new PropBuilder()
        .setName("tags")
        .setKind("array")
        .setHidden(false)
        .setWidget(new PropWidgetDefinitionBuilder()
            .setKind("array")
            .build())
        .setEntry(
            new PropBuilder()
            .setName("tags_item")
            .setKind("string")
            .setWidget(new PropWidgetDefinitionBuilder().setKind("text").build())
            .build()
        )
        .setValidationFormat(Joi.array().items(Joi.string()).required())
        .setDocumentation("An array of tag names. The alert policy will apply to all resources that have these tags applied.")
        .build();

    // Enabled property (required)
    const enabledProp = new PropBuilder()
        .setName("enabled")
        .setKind("boolean")
        .setHidden(false)
        .setWidget(new PropWidgetDefinitionBuilder()
            .setKind("checkbox")
            .build())
        .setValidationFormat(Joi.boolean().required())
        .setDocumentation("A boolean indicating whether the alert policy is enabled and will trigger alerts.")
        .build();

    // Alerts object - Email array property
    const alertsEmailProp = new PropBuilder()
        .setName("email")
        .setKind("array")
        .setHidden(false)
        .setWidget(new PropWidgetDefinitionBuilder()
            .setKind("array")
            .build())
        .setEntry(
            new PropBuilder()
            .setName("email_item")
            .setKind("string")
            .setWidget(new PropWidgetDefinitionBuilder().setKind("text").build())
            .setValidationFormat(Joi.string().email())
            .setDocumentation("Email address to notify")
            .build()
        )
        .setValidationFormat(Joi.array().items(Joi.string().email()).required())
        .setDocumentation("An array of email addresses to notify when the alert is triggered.")
        .build();

    // Alerts object - Slack details URL property
    const alertsSlackUrlProp = new PropBuilder()
        .setName("url")
        .setKind("string")
        .setHidden(false)
        .setWidget(new PropWidgetDefinitionBuilder()
            .setKind("text")
            .build())
        .setValidationFormat(Joi.string().uri())
        .setDocumentation("Slack webhook URL for notifications.")
        .build();

    // Alerts object - Slack details channel property
    const alertsSlackChannelProp = new PropBuilder()
        .setName("channel")
        .setKind("string")
        .setHidden(false)
        .setWidget(new PropWidgetDefinitionBuilder()
            .setKind("text")
            .build())
        .setValidationFormat(Joi.string())
        .setDocumentation("Slack channel name to notify.")
        .build();

    // Alerts object - Slack details object
    const alertsSlackProp = new PropBuilder()
        .setName("slack_details")
        .setKind("object")
        .setHidden(false)
        .setWidget(new PropWidgetDefinitionBuilder()
            .setKind("header")
            .build())
        .addChild(alertsSlackUrlProp)
        .addChild(alertsSlackChannelProp)
        .setDocumentation("Slack integration details for alert notifications.")
        .build();

    // Alerts object - Slack array property
    const alertsSlackArrayProp = new PropBuilder()
        .setName("slack")
        .setKind("array")
        .setHidden(false)
        .setWidget(new PropWidgetDefinitionBuilder()
            .setKind("array")
            .build())
        .setEntry(alertsSlackProp)
        .setValidationFormat(Joi.array().items(Joi.object({
            url: Joi.string().uri().required(),
            channel: Joi.string().required()
        })).required())
        .setDocumentation("An array of Slack integration configurations for alert notifications.")
        .build();

    // Main Alerts object property (required)
    const alertsProp = new PropBuilder()
        .setName("alerts")
        .setKind("object")
        .setHidden(false)
        .setWidget(new PropWidgetDefinitionBuilder()
            .setKind("header")
            .build())
        .addChild(alertsEmailProp)
        .addChild(alertsSlackArrayProp)
        .setDocumentation("Alert notification configuration including email addresses and Slack integrations.")
        .build();

    // Create the asset
    const asset = new AssetBuilder()
        .addProp(typeProp)
        .addProp(descriptionProp)
        .addProp(compareProp)
        .addProp(valueProp)
        .addProp(windowProp)
        .addProp(entitiesProp)
        .addProp(tagsProp)
        .addProp(enabledProp)
        .addProp(alertsProp)
        .addSecretProp(DOCredentialSecretProp)
        .build();

    return asset;
}