function main() {
    // DigitalOcean API Token secret
    const DOCredentialSecretProp = new SecretPropBuilder()
        .setName("DigitalOcean Credential")
        .setSecretKind("DigitalOcean Credential")
        .build();

    // Name property (required)
    const nameProp = new PropBuilder()
        .setName("name")
        .setKind("string")
        .setHidden(false)
        .setWidget(new PropWidgetDefinitionBuilder()
            .setKind("text")
            .setCreateOnly()
            .build())
        .setValidationFormat(Joi.string().required().max(255).pattern(/^[a-zA-Z0-9_\-\:]+$/))
        .setDocumentation("The name of the tag. Tags may contain letters, numbers, colons, dashes, and underscores. There is a limit of 255 characters per tag. Tag names are case stable, which means the capitalization you use when you first create a tag is canonical.")
        .build();

    // Resources property (read-only metadata)
    const resourcesProp = new PropBuilder()
        .setName("resources")
        .setKind("object")
        .setHidden(false)
        .setWidget(new PropWidgetDefinitionBuilder()
            .setKind("header")
            .build())
        .addChild(
            new PropBuilder()
                .setName("count")
                .setKind("float")
                .setWidget(new PropWidgetDefinitionBuilder()
                    .setKind("text")
                    .build())
                .setValidationFormat(Joi.number().integer().min(0))
                .setDocumentation("The number of tagged objects for this resource.")
                .build()
        )
        .addChild(
            new PropBuilder()
                .setName("last_tagged_uri")
                .setKind("string")
                .setWidget(new PropWidgetDefinitionBuilder()
                    .setKind("text")
                    .build())
                .setValidationFormat(Joi.string().uri())
                .setDocumentation("The URI for the last tagged object for this resource.")
                .build()
        )
        .addChild(
            new PropBuilder()
                .setName("droplets")
                .setKind("object")
                .setWidget(new PropWidgetDefinitionBuilder()
                    .setKind("header")
                    .build())
                .addChild(
                    new PropBuilder()
                        .setName("count")
                        .setKind("float")
                        .setWidget(new PropWidgetDefinitionBuilder()
                            .setKind("text")
                            .build())
                        .setValidationFormat(Joi.number().integer().min(0))
                        .setDocumentation("Droplets that are tagged with the specified tag. Requires droplet:read scope.")
                        .build()
                )
                .addChild(
                    new PropBuilder()
                        .setName("last_tagged_uri")
                        .setKind("string")
                        .setWidget(new PropWidgetDefinitionBuilder()
                            .setKind("text")
                            .build())
                        .setValidationFormat(Joi.string().uri())
                        .setDocumentation("The URI for the last tagged Droplet.")
                        .build()
                )
                .setDocumentation("Droplets that are tagged with the specified tag.")
                .build()
        )
        .addChild(
            new PropBuilder()
                .setName("images")
                .setKind("object")
                .setWidget(new PropWidgetDefinitionBuilder()
                    .setKind("header")
                    .build())
                .addChild(
                    new PropBuilder()
                        .setName("count")
                        .setKind("float")
                        .setWidget(new PropWidgetDefinitionBuilder()
                            .setKind("text")
                            .build())
                        .setValidationFormat(Joi.number().integer().min(0))
                        .setDocumentation("Images that are tagged with the specified tag. Requires image:read scope.")
                        .build()
                )
                .addChild(
                    new PropBuilder()
                        .setName("last_tagged_uri")
                        .setKind("string")
                        .setWidget(new PropWidgetDefinitionBuilder()
                            .setKind("text")
                            .build())
                        .setValidationFormat(Joi.string().uri())
                        .setDocumentation("The URI for the last tagged Image.")
                        .build()
                )
                .setDocumentation("Images that are tagged with the specified tag.")
                .build()
        )
        .addChild(
            new PropBuilder()
                .setName("volumes")
                .setKind("object")
                .setWidget(new PropWidgetDefinitionBuilder()
                    .setKind("header")
                    .build())
                .addChild(
                    new PropBuilder()
                        .setName("count")
                        .setKind("float")
                        .setWidget(new PropWidgetDefinitionBuilder()
                            .setKind("text")
                            .build())
                        .setValidationFormat(Joi.number().integer().min(0))
                        .setDocumentation("Volumes that are tagged with the specified tag. Requires block_storage:read scope.")
                        .build()
                )
                .addChild(
                    new PropBuilder()
                        .setName("last_tagged_uri")
                        .setKind("string")
                        .setWidget(new PropWidgetDefinitionBuilder()
                            .setKind("text")
                            .build())
                        .setValidationFormat(Joi.string().uri())
                        .setDocumentation("The URI for the last tagged Volume.")
                        .build()
                )
                .setDocumentation("Volumes that are tagged with the specified tag.")
                .build()
        )
        .addChild(
            new PropBuilder()
                .setName("volume_snapshots")
                .setKind("object")
                .setWidget(new PropWidgetDefinitionBuilder()
                    .setKind("header")
                    .build())
                .addChild(
                    new PropBuilder()
                        .setName("count")
                        .setKind("float")
                        .setWidget(new PropWidgetDefinitionBuilder()
                            .setKind("text")
                            .build())
                        .setValidationFormat(Joi.number().integer().min(0))
                        .setDocumentation("Volume snapshots that are tagged with the specified tag. Requires block_storage_snapshot:read scope.")
                        .build()
                )
                .addChild(
                    new PropBuilder()
                        .setName("last_tagged_uri")
                        .setKind("string")
                        .setWidget(new PropWidgetDefinitionBuilder()
                            .setKind("text")
                            .build())
                        .setValidationFormat(Joi.string().uri())
                        .setDocumentation("The URI for the last tagged Volume Snapshot.")
                        .build()
                )
                .setDocumentation("Volume snapshots that are tagged with the specified tag.")
                .build()
        )
        .addChild(
            new PropBuilder()
                .setName("databases")
                .setKind("object")
                .setWidget(new PropWidgetDefinitionBuilder()
                    .setKind("header")
                    .build())
                .addChild(
                    new PropBuilder()
                        .setName("count")
                        .setKind("float")
                        .setWidget(new PropWidgetDefinitionBuilder()
                            .setKind("text")
                            .build())
                        .setValidationFormat(Joi.number().integer().min(0))
                        .setDocumentation("Databases that are tagged with the specified tag. Requires database:read scope.")
                        .build()
                )
                .addChild(
                    new PropBuilder()
                        .setName("last_tagged_uri")
                        .setKind("string")
                        .setWidget(new PropWidgetDefinitionBuilder()
                            .setKind("text")
                            .build())
                        .setValidationFormat(Joi.string().uri())
                        .setDocumentation("The URI for the last tagged Database.")
                        .build()
                )
                .setDocumentation("Databases that are tagged with the specified tag.")
                .build()
        )
        .setDocumentation("An embedded object containing key value pairs of resource type and resource statistics. It also includes a count of the total number of resources tagged with the current tag as well as a last_tagged_uri attribute set to the last resource tagged with the current tag. This will only include resources that you are authorized to see.")
        .build();

    // Create the asset
    const asset = new AssetBuilder()
        .addProp(nameProp)
        .addResourceProp(resourcesProp)
        .addSecretProp(DOCredentialSecretProp)
        .build();

    return asset;
}